# Generated by Django 4.2.20 on 2025-04-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1024)),
                ('img', models.ImageField(blank='True', null='True', upload_to='myapp/')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
